#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $X_REPO == "X-USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1gtVVNFUkJPVC9YLU1BSU4vYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $X_REPO == "X-USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1gtVVNFUkJPVC9YLU1BSU4vYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $X_REPO =~ $regex ]]
    then
        if [[ $X_REPO_BRANCH ]]
        then
            echo "${X_REPO}/archive/${X_REPO_BRANCH}.zip"
        else
            echo "${X_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1gtVVNFUkJPVC9YLU1BSU4vYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myxbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    XPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $XPATH
    echo "  • Starting X Bot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m xbot
}

start_bot
